### ISSUE TITLE
No Online Documentation

### ISSUE THREAD

**Issue by stadler** [vaadin/maven-plugin#99] opened 2017-05-05 10:07 UTC
Hi

I often want to check the documentation of certain goals of this plugin, but unfortunately I cannot find any. :(

As a workaround I use the standard maven plugin mechanism: `mvn com.vaadin:vaadin-maven-plugin:help`.
Doing this with java 7 crashes. With Java 8 it works and returns proper documentation.

However it would be nice to have this documentation online. It should be possible to generate it with the [maven-plugin-plugin](http://maven.apache.org/plugins/maven-plugin-plugin/). See the [Guide to the Plugin Documentation Standard](http://maven.apache.org/guides/development/guide-plugin-documentation.html) for how it is done.
The only thing that would be left to do would be to upload those pages into the github wiki (or some other place).

Thanks!

**Comment by focbenz** [comment] 2017-05-29 06:35
The old documentation was made available thorugh codehaus.org which is shut down now.
But I would also second a new home for the documentation somewhere accessible.
https://github.com/vaadin/maven-plugin/blob/master/README.md

Duplicate: https://github.com/vaadin/maven-plugin/issues/79

**Comment by Legioth** [comment] 2017-05-30 05:19
Closing as a duplicate of #79.

**Closed by Legioth** 2017-05-30 05:19 UTC
